name:                mlMinus
version:             0.1.0.0
github:              "githubuser/mlMinus"
license:             BSD-3-Clause
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2025 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/mlMinus#readme>

dependencies:
- base >= 4.7 && < 5
- generic-lens
- microlens
- mtl

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  default-extensions:
  - ImportQualifiedPost
  - OverloadedStrings
  - OverloadedLists
  - BlockArguments
  - TupleSections
  - BangPatterns
  - LambdaCase
  - DuplicateRecordFields
  - OverloadedRecordDot
  - OverloadedLabels
  - NoFieldSelectors
  - RecordWildCards
  - NamedFieldPuns
  - FlexibleContexts
  - TypeApplications
  - DeriveGeneric
  - DataKinds
  - DeriveAnyClass
  - ConstraintKinds
  - StandaloneDeriving
  - ScopedTypeVariables
  - MultiWayIf
  - GeneralizedNewtypeDeriving
  - DerivingStrategies
  - MultiParamTypeClasses
  - FunctionalDependencies

executables:
  mlMinus-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mlMinus
    default-extensions:
    - ImportQualifiedPost
    - OverloadedStrings
    - OverloadedLists
    - BlockArguments
    - TupleSections
    - BangPatterns
    - LambdaCase
    - DuplicateRecordFields
    - OverloadedRecordDot
    - OverloadedLabels
    - NoFieldSelectors
    - RecordWildCards
    - NamedFieldPuns
    - FlexibleContexts
    - TypeApplications
    - DeriveGeneric
    - DataKinds
    - DeriveAnyClass
    - ConstraintKinds
    - StandaloneDeriving
    - ScopedTypeVariables
    - MultiWayIf
    - GeneralizedNewtypeDeriving
    - DerivingStrategies
    - MultiParamTypeClasses
    - FunctionalDependencies

tests:
  mlMinus-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mlMinus
